Make sure to use none backends in generated C code
Otherwise you might run into this:

    Message from VCC-compiler:
    Unused backend nil, defined:
    ('<vcl.inline>' Line 4 Pos 17)
            backend nil none;
    ----------------###------

    (That was just a warning)
    Message from C-compiler:
    vgc.c:1476:20: error: unused variable 'vgc_backend_nil' [-Werror,-Wunused-variable]
    static VCL_BACKEND vgc_backend_nil;
                       ^
    1 error generated.
    Running C-compiler failed, exited with 1
    VCL compilation failed

This is done in both init and discard code to maintain the balance.