exit VFIL_searchpath upon dlopen error
Together with the previous commit, this fixes potentially misleading
error messages.

Because we called vcc_path_dlopen on all vmod_path elements
irrespective of the kind of dlopen() error, the actual root cause
could be hidden.

Example:

dlerror: .../lib/libvmod_blob/.libs/libvmod_debug.so: cannot open shared object file

when the actual error was

dlerror: .../lib/libvmod_debug/.libs/libvmod_debug.so: undefined symbol:...