Add NO_CHECK_OBJ macro to neuter CHECK_OBJ
The CHECK_OBJ*() macros are great, and no-one could ever want to live without
them, but they have one disadvantage: They prevent compiler warnings about
unused variables.

So, for this purpose only, we add NO_CHECK_OBJ to discover more unused
variables:

$ make CFLAGS='-DNO_CHECK_OBJ -Wall -Werror'
...
cache/cache_gzip.c:420:17: error: variable 'wrk' set but not used [-Werror,-Wunused-but-set-variable]
        struct worker *wrk;