jail_unix: Improve error reporting of failed chown()
Before this patch, configuring an existing read only directory as the working
directory would result in an assertion failure:

$ mount | grep /tmp/ro
swap on /tmp/ro type tmpfs (ro,relatime,inode64)

$ sudo /tmp/sbin/varnishd -j unix -n /tmp/ro -a @a -b @b
Assert error in vju_make_workdir(), mgt/mgt_jail_unix.c line 277:
  Condition((chown(dname, -1, vju_gid)) == 0) not true.
  errno = 30 (Read-only file system)

This is now changed to:

$ sudo /tmp/sbin/varnishd -j unix -n /tmp/ro -a @a -b @b
Error: Cannot change group of working directory '/tmp/ro': Read-only file system
(-? gives usage)

Note: There are more {f,}chown calls in AZ(), but under the traditional model of
a super cow powered uid 0, they should, I think, succeed once chown() of the
working directory itself succeeded.