properly declare vtc_h2_dectbl.h to automake and git
in order to have it build first and cleaned up

fixes this issue when switching to an older branch:

$ git checkout ...
error: The following untracked working tree files would be overwritten
by checkout:
	bin/varnishtest/vtc_h2_dectbl.h
Please move or remove them before you switch branches.
Aborting